CREATE SEQUENCE customerIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE managerIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE scheduleIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE flightIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE loyaltyIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE delayIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE refundIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE ticketIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

CREATE SEQUENCE luggageIDseq
   START WITH 1
   INCREMENT BY 1
   NOMAXVALUE;

COMMIT;