--Tables
DROP TABLE LUGGAGE;
DROP TABLE TICKETS;
DROP TABLE REFUNDS;
DROP TABLE DELAYS;
DROP TABLE LOYALTY;
DROP TABLE FLIGHTS;
DROP TABLE SCHEDULES;
DROP TABLE MANAGERS;
DROP TABLE AIRPORTS;
DROP TABLE CUSTOMERS;
DROP TABLE SEATS;
DROP TABLE STATES;

--Views
DROP VIEW SeatMap;
DROP VIEW DepartureBoard;
DROP VIEW LoyaltyProgram;
DROP VIEW Finances;
DROP VIEW CustomerLocation;
DROP VIEW FlightView;

--Sequences
ALTER SEQUENCE CUSTOMERIDSEQ START WITH 1;
ALTER SEQUENCE MANAGERIDSEQ START WITH 1;
ALTER SEQUENCE DELAYIDSEQ START WITH 1;
ALTER SEQUENCE FLIGHTIDSEQ START WITH 1;
ALTER SEQUENCE LOYALTYIDSEQ START WITH 1;
ALTER SEQUENCE LUGGAGEIDSEQ START WITH 1;
ALTER SEQUENCE REFUNDIDSEQ START WITH 1;
ALTER SEQUENCE SCHEDULEIDSEQ START WITH 1;
ALTER SEQUENCE TICKETIDSALTER START WITH 1;

DROP SEQUENCE CUSTOMERIDSEQ;
DROP SEQUENCE MANAGERIDSEQ;
DROP SEQUENCE DELAYIDSEQ;
DROP SEQUENCE FLIGHTIDSEQ;
DROP SEQUENCE LOYALTYIDSEQ;
DROP SEQUENCE LUGGAGEIDSEQ;
DROP SEQUENCE REFUNDIDSEQ;
DROP SEQUENCE SCHEDULEIDSEQ;
DROP SEQUENCE TICKETIDSEQ;

--Triggers
DROP TRIGGER CUSTOMERIDTRIGGER;
DROP TRIGGER MANAGERIDTRIGGER;
DROP TRIGGER DELAYIDTRIGGER;
DROP TRIGGER FLIGHTIDTRIGGER;
DROP TRIGGER LOYALTYIDTRIGGER;
DROP TRIGGER LUGGAGEIDTRIGGER;
DROP TRIGGER REFUNDIDTRIGGER;
DROP TRIGGER SCHEDULEIDTRIGGER;
DROP TRIGGER TICKETIDTRIGGER;

--Indexes
DROP INDEX scheduleIndex;
DROP INDEX flightIndex;
DROP INDEX loyaltyIndex;
DROP INDEX delayIndex;
DROP INDEX refundIndex;
DROP INDEX ticketIndex;
DROP INDEX luggageIndex;